Table role {  
  id int [pk]  
  name varchar
}  

Table users {  
  id int [pk]  
  username varchar
  password varchar
  email varchar
  phone varchar
  profile_image varchar
  role_id int [ref: > role.id]
}  

Table dosen {  
  id int [pk]
  nip varchar
  name varchar
  email varchar
  telepon varchar
  jabatan varchar
}  

Table ujian_proposal {  
  id int [pk]  
  dosen_id int  
}  

Table proposal {  
  id int [pk]  
  judul varchar
  komentar varchar
  nilai varchar
  tugas_akhir_id int  
  periode_proposal_id int  
  tanggal_pengajuan varchar
  mahasiswa_id int  
}  

Table tugas_akhir {  
  id int [pk]  
  judul varchar
  berkas varchar
  status varchar
  mahasiswa_id int  
  pembimbing1_id int  
  pembimbing2_id int  
  penguji1_id int  
  penguji2_id int  
  tanggal_pengajuan varchar
}  

Table periode_proposal {  
  id int [pk]  
  name varchar
  start_date timestamp
  end_data timestamp
  is_active bool
}

Table unsur_penilaian {  
  id int [pk]  
  nama VARCHAR(255)  
  bobot DECIMAL(5,2)  
}  

Table penilaian {  
  id int [pk]  
  unsur_penilaian_id int  
  skor int  
  proposal_id int
  tugas_akhir_id int
}  
