Table roles {
  id int [pk]
  name varchar
}

Table generations {
  id int [pk]
  name varchar
}

Table users {
  id int [pk]
  identity varchar
  password varchar
  email varchar
  phone varchar
  profile_image varchar
  generation_id int [ref: > generations.id]
  role_id int [ref: > roles.id]
}

Table final_project_period {
  id int [pk]
  name varchar
  start_date date
  end_date date
  is_active bool
  generation_id int [ref: > generations.id]
}

Table evaluation {
  id int [pk]
  name varchar
}

Table evaluation_criteria {
  id int [pk]
  name varchar
  score decimal
  evaluation_id int [ref: > evaluation.id]
}

Table sub_evaluation_criteria {
  id int [pk]
  name varchar
  score decimal
  evaluation_criteria_id int [ref: > evaluation_criteria.id]
}

Table final_project {
  id int [pk]
  title varchar
  document varchar
  support_document varchar
  final_project_period_id int [ref: > final_project_period.id]
}

Table exams {
  id int [pk]
  exam_date date
  start_time time
  end_time time
  room varchar
  status bool
  student_id int [ref: > users.id]
  primary_examiner_id int [ref: > users.id]
  secondary_examiner_id int [ref: > users.id]
  tertiary_examiner_id int [ref: > users.id]
}

Table exam_evaluations {
  id int [pk]
  student_id int [ref: > users.id]
  examiner_id int [ref: > users.id]
  evaluation_id int [ref: > evaluation.id]
  exam_id int [ref: > exams.id]
}

Table evaluation_scores {
  id int [pk, increment]
  exam_evaluation_id int [ref: > exam_evaluation.id]
  evaluation_criteria_id int [ref: > evaluation_criteria.id]
  score decimal
}
